%%
% Compile fast exp/log C++ mex code for 2x2 tensors.

mex toolbox_quantum/tensor_logexp/tensorLog2x2.cpp ...
    -outdir toolbox_quantum/tensor_logexp -largeArrayDims ...
    -v COMPFLAGS="$COMPFLAGS /fp:fast /openmp" ...
    OPTIMFLAGS="$OPTIMFLAGS /Ox /openmp"

mex toolbox_quantum/tensor_logexp/tensorExp2x2.cpp ...
    -outdir toolbox_quantum/tensor_logexp -largeArrayDims ...
    -v COMPFLAGS="$COMPFLAGS /fp:fast /openmp" ...
    OPTIMFLAGS="$OPTIMFLAGS /Ox /openmp"